<?php

namespace AppBundle\Entity\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * CrawlerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerRepository extends EntityRepository
{
}
