version: '2'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
      - "443:443"
    links:
      - php
      - mysql
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./httpdocs:/var/www
    container_name: test-marfeel_web

  php:
    image: dember/php-symfony:php7
    working_dir: /var/www
    volumes:
      - ./httpdocs:/var/www
      - ./conf/php.ini:/etc/php/7.1/fpm/conf.d/40-custom.ini
    links:
      - mysql
    container_name: test-marfeel_php

  mysql:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=HBARvEra8pT7X4NP
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=StENCngfMk5dQU6x
    container_name: test-marfeel_mysql